name: CI Node pipeline for isEven
on:
  push:
    branches:
       - main
    
  pull_request:
      branches:
       - main


jobs:
  isEven:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses:  actions/checkout@v3

      - name: Set up node js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run test
        run: npm test

      - name: Package build output as zip
        run: |
          mkdir output
          cp -r src output/
          cp package.json output
          zip -r build.zip output

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-zip
          path: build.zip
      
      - name: Notify Success via email
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: sujeet05kp@gmail.com
          password: your app password
          subject: "CI  Build success-${{github.repository}}"
          body: |
            The build for ${{github.repository}} on branch ${{github.ref_name}} succeeded.
            commit: ${{github.sha}} |
          to: sujeet05kp@gmail.com
          from: sujeet05kp@gmail.com